version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - DATABASE_URL = postgres://rtxhwzxy:2FAMPP9VnYJjEmsXCGQFKME39B1mnlMz@tiny.db.elephantsql.com/rtxhwzxy
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
  api:
    image: node:slim
    build: .
    depends_on:
      - db
    ports: 
      - "3000:3000"
    command: "npm run start:dev"

      